### PR TITLE
Fixes argument definition for terraform v0.12

### PR DESCRIPTION
**Pull request by MainAero**
This PR adds support for terraform v0.12

### CODE REVIEW

**Comment by Napas** [comment]
@squidfunk could you please merge this one in?

**Comment by squidfunk** [comment]
GitHub somehow didn't notify me on this PR. Merged, will issue a new release in a minute.

**Comment by Napas** [comment]
That was fast, cheers! :)

**Comment by squidfunk** [comment]
Released as part of [0.3.0](https://github.com/squidfunk/terraform-aws-api-gateway-enable-cors/releases/tag/0.3.0).

**Pull request merged**
