### PR TITLE
added support for access-control-allow-credentials header

### PR DESCRIPTION
**Pull request by kudla**
Hi Martin!

I'm happy to use your pretty cool module and I'm looking forward you to merge this commit to add `Access-Control-Allow-Credentials` header feature support to it.

Can't wait since I have dependencies on it please.
Thx!

### CODE REVIEW

**Comment by squidfunk** [comment]
Thanks for your PR. Actually, you made a lot of changes. Care to elaborate what and why? I see a new integration response - is that necessary?

**Comment by kudla** [comment]
And the basic idea is to manage `Access-Control-Allow-Credentials` header appearance in the `OPTIONS` response by boolean flag variable of module named [allow_credentials](https://github.com/squidfunk/terraform-aws-api-gateway-enable-cors/pull/3/commits/6640071dbdf8a0042a59befe18a8e36854ab9247#diff-c9ac8098c5ea9d3e6a9a596ff0c512a4R84)

**Comment by squidfunk** [comment]
Hmm, actually I would prefer just setting the header on the integration response and excluding it on the method response (via the variable). No further resources will be needed at the cost of one header in the integration response. Haven't tested it, but I think it should work.

**Comment by kudla** [comment]
As far as I've tried it seems we ca not exclude it just toggling the value as
```
    "method.response.header.Access-Control-Allow-Credentials" = "${var.allow_credentials}"
```
This case it stays at method response anyway. So need just explicitly omit the declaration and ought to keep dual declaration for method response.
But I can be wrong. Will check later tonight.

**Comment by squidfunk** [comment]
Maybe we can use [`zipmap`](https://www.terraform.io/docs/configuration/interpolation.html#zipmap-list-list-) and `locals` to reduce duplication. `response-parameters` is a map, so preparing the response headers in `locals` and referencing them might work. This way we could set all headers with `true` on the method response and define them conditionally on the integration response. I will test it when I find the time.

Also I found this workaround, which might also work:
https://github.com/jaceq/terraform-examples/blob/master/examples/conditional-map.tf

**Comment by kudla** [comment]
Came up with way more compact solution

**Comment by kudla** [comment]
Martin, I made it even more flexible!
No we just can add what ever new header to support and it will just filter any header that is evaluated with empty value.

**Comment by squidfunk** [comment]
Thanks a ton for your work! Really awesome that `zipmap` seems to do the job - didn't knew about this before. I will merge it tomorrow.

**Comment by squidfunk** [comment]
Thanks for your PR! I tested it and it works perfect. It will be part of 0.2.0, which will be released in a short moment.

**Comment by squidfunk** [comment]
Note that I also renamed the variables from `allowed_*` to `allow_*`, as it more closely mimics the name of the header.

**Pull request merged**
